from __future__ import annotations

# Complete Places365 -> project scene-group mapping.
#
# Labels are normalized in the same way as vocabularies.normalize_scene_label():
# lowercase, underscores -> spaces, slashes -> spaces.
#
# The goal is not to reproduce Places365 taxonomy exactly, but to map every
# Places365 class to the soundscape-oriented scene families used in Workflow B.

PLACES365_TO_SCENE_GROUP: dict[str, str] = {
    # ------------------------------------------------------------------
    # Rural / traditional / vernacular environments
    # ------------------------------------------------------------------
    "barn": "rural_traditional",
    "barndoor": "rural_traditional",
    "cabin outdoor": "rural_traditional",
    "campsite": "rural_traditional",
    "chalet": "rural_traditional",
    "corn field": "rural_traditional",
    "corral": "rural_traditional",
    "cottage": "rural_traditional",
    "farm": "rural_traditional",
    "field cultivated": "rural_traditional",
    "field wild": "rural_traditional",
    "field road": "rural_traditional",
    "hayfield": "rural_traditional",
    "hunting lodge outdoor": "rural_traditional",
    "igloo": "rural_traditional",
    "kennel outdoor": "rural_traditional",
    "manufactured home": "rural_traditional",
    "oast house": "rural_traditional",
    "orchard": "rural_traditional",
    "pasture": "rural_traditional",
    "rice paddy": "rural_traditional",
    "schoolhouse": "rural_traditional",
    "shed": "rural_traditional",
    "stable": "rural_traditional",
    "tree farm": "rural_traditional",
    "tree house": "rural_traditional",
    "vegetable garden": "rural_traditional",
    "village": "rural_traditional",
    "vineyard": "rural_traditional",
    "wheat field": "rural_traditional",
    "windmill": "rural_traditional",
    "yard": "rural_traditional",

    # ------------------------------------------------------------------
    # Natural outdoor / landscape scenes
    # ------------------------------------------------------------------
    "badlands": "natural_outdoor",
    "bamboo forest": "natural_outdoor",
    "butte": "natural_outdoor",
    "canyon": "natural_outdoor",
    "cliff": "natural_outdoor",
    "crevasse": "natural_outdoor",
    "desert sand": "natural_outdoor",
    "desert vegetation": "natural_outdoor",
    "forest broadleaf": "natural_outdoor",
    "forest path": "natural_outdoor",
    "forest road": "natural_outdoor",
    "glacier": "natural_outdoor",
    "grotto": "natural_outdoor",
    "hot spring": "natural_outdoor",
    "ice floe": "natural_outdoor",
    "ice shelf": "natural_outdoor",
    "iceberg": "natural_outdoor",
    "islet": "natural_outdoor",
    "lawn": "natural_outdoor",
    "marsh": "natural_outdoor",
    "mountain": "natural_outdoor",
    "mountain path": "natural_outdoor",
    "mountain snowy": "natural_outdoor",
    "park": "natural_outdoor",
    "rainforest": "natural_outdoor",
    "rock arch": "natural_outdoor",
    "sky": "natural_outdoor",
    "snowfield": "natural_outdoor",
    "swamp": "natural_outdoor",
    "trench": "natural_outdoor",
    "tundra": "natural_outdoor",
    "valley": "natural_outdoor",
    "volcano": "natural_outdoor",

    # ------------------------------------------------------------------
    # Market / retail / public commercial scenes
    # ------------------------------------------------------------------
    "bakery shop": "market_public",
    "bazaar indoor": "market_public",
    "bazaar outdoor": "market_public",
    "beauty salon": "market_public",
    "bookstore": "market_public",
    "booth indoor": "market_public",
    "butchers shop": "market_public",
    "candy store": "market_public",
    "clothing store": "market_public",
    "coffee shop": "market_public",
    "delicatessen": "market_public",
    "department store": "market_public",
    "drugstore": "market_public",
    "fabric store": "market_public",
    "fastfood restaurant": "market_public",
    "flea market indoor": "market_public",
    "florist shop indoor": "market_public",
    "food court": "market_public",
    "general store indoor": "market_public",
    "general store outdoor": "market_public",
    "gift shop": "market_public",
    "hardware store": "market_public",
    "ice cream parlor": "market_public",
    "jewelry shop": "market_public",
    "market indoor": "market_public",
    "market outdoor": "market_public",
    "pet shop": "market_public",
    "pharmacy": "market_public",
    "pizzeria": "market_public",
    "restaurant": "market_public",
    "restaurant patio": "market_public",
    "shoe shop": "market_public",
    "shopfront": "market_public",
    "shopping mall indoor": "market_public",
    "supermarket": "market_public",
    "sushi bar": "market_public",
    "toyshop": "market_public",

    # ------------------------------------------------------------------
    # Religious / heritage / monumental scenes
    # ------------------------------------------------------------------
    "aqueduct": "religious_heritage",
    "arch": "religious_heritage",
    "archaelogical excavation": "religious_heritage",
    "burial chamber": "religious_heritage",
    "castle": "religious_heritage",
    "catacomb": "religious_heritage",
    "cemetery": "religious_heritage",
    "church indoor": "religious_heritage",
    "church outdoor": "religious_heritage",
    "courthouse": "religious_heritage",
    "excavation": "religious_heritage",
    "kasbah": "religious_heritage",
    "mausoleum": "religious_heritage",
    "medina": "religious_heritage",
    "mosque outdoor": "religious_heritage",
    "pagoda": "religious_heritage",
    "palace": "religious_heritage",
    "ruin": "religious_heritage",
    "synagogue outdoor": "religious_heritage",
    "temple asia": "religious_heritage",
    "throne room": "religious_heritage",

    # ------------------------------------------------------------------
    # Indoor domestic / residential scenes
    # ------------------------------------------------------------------
    "alcove": "indoor_domestic",
    "apartment building outdoor": "indoor_domestic",
    "attic": "indoor_domestic",
    "balcony interior": "indoor_domestic",
    "basement": "indoor_domestic",
    "bathroom": "indoor_domestic",
    "beach house": "indoor_domestic",
    "bedchamber": "indoor_domestic",
    "bedroom": "indoor_domestic",
    "bow window indoor": "indoor_domestic",
    "childs room": "indoor_domestic",
    "closet": "indoor_domestic",
    "dining room": "indoor_domestic",
    "doorway outdoor": "indoor_domestic",
    "dorm room": "indoor_domestic",
    "dressing room": "indoor_domestic",
    "galley": "indoor_domestic",
    "garage indoor": "indoor_domestic",
    "garage outdoor": "indoor_domestic",
    "home office": "indoor_domestic",
    "home theater": "indoor_domestic",
    "hotel room": "indoor_domestic",
    "house": "indoor_domestic",
    "jacuzzi indoor": "indoor_domestic",
    "kitchen": "indoor_domestic",
    "laundromat": "indoor_domestic",
    "living room": "indoor_domestic",
    "mansion": "indoor_domestic",
    "nursery": "indoor_domestic",
    "pantry": "indoor_domestic",
    "patio": "indoor_domestic",
    "playroom": "indoor_domestic",
    "porch": "indoor_domestic",
    "recreation room": "indoor_domestic",
    "residential neighborhood": "indoor_domestic",
    "restaurant kitchen": "indoor_domestic",
    "sauna": "indoor_domestic",
    "shower": "indoor_domestic",
    "staircase": "indoor_domestic",
    "storage room": "indoor_domestic",
    "television room": "indoor_domestic",
    "utility room": "indoor_domestic",
    "wet bar": "indoor_domestic",
    "youth hostel": "indoor_domestic",

    # ------------------------------------------------------------------
    # Urban / transport / mobility scenes
    # ------------------------------------------------------------------
    "airfield": "urban_transport",
    "airplane cabin": "urban_transport",
    "airport terminal": "urban_transport",
    "alley": "urban_transport",
    "auto showroom": "urban_transport",
    "balcony exterior": "urban_transport",
    "boardwalk": "urban_transport",
    "bridge": "urban_transport",
    "building facade": "urban_transport",
    "bus interior": "urban_transport",
    "bus station indoor": "urban_transport",
    "car interior": "urban_transport",
    "cockpit": "urban_transport",
    "crosswalk": "urban_transport",
    "desert road": "urban_transport",
    "downtown": "urban_transport",
    "driveway": "urban_transport",
    "embassy": "urban_transport",
    "fire escape": "urban_transport",
    "fire station": "urban_transport",
    "gas station": "urban_transport",
    "hangar indoor": "urban_transport",
    "hangar outdoor": "urban_transport",
    "heliport": "urban_transport",
    "highway": "urban_transport",
    "hotel outdoor": "urban_transport",
    "inn outdoor": "urban_transport",
    "landing deck": "urban_transport",
    "lighthouse": "urban_transport",
    "lock chamber": "urban_transport",
    "motel": "urban_transport",
    "office building": "urban_transport",
    "parking garage indoor": "urban_transport",
    "parking garage outdoor": "urban_transport",
    "parking lot": "urban_transport",
    "phone booth": "urban_transport",
    "plaza": "urban_transport",
    "promenade": "urban_transport",
    "raceway": "urban_transport",
    "railroad track": "urban_transport",
    "rope bridge": "urban_transport",
    "runway": "urban_transport",
    "skyscraper": "urban_transport",
    "slum": "urban_transport",
    "street": "urban_transport",
    "subway station platform": "urban_transport",
    "ticket booth": "urban_transport",
    "tower": "urban_transport",
    "train interior": "urban_transport",
    "train station platform": "urban_transport",
    "viaduct": "urban_transport",
    "water tower": "urban_transport",

    # ------------------------------------------------------------------
    # Coastal / water scenes
    # ------------------------------------------------------------------
    "aquarium": "coastal_water",
    "beach": "coastal_water",
    "boat deck": "coastal_water",
    "boathouse": "coastal_water",
    "canal natural": "coastal_water",
    "canal urban": "coastal_water",
    "coast": "coastal_water",
    "creek": "coastal_water",
    "dam": "coastal_water",
    "fishpond": "coastal_water",
    "harbor": "coastal_water",
    "lagoon": "coastal_water",
    "lake natural": "coastal_water",
    "moat water": "coastal_water",
    "ocean": "coastal_water",
    "pier": "coastal_water",
    "pond": "coastal_water",
    "raft": "coastal_water",
    "river": "coastal_water",
    "swimming hole": "coastal_water",
    "underwater ocean deep": "coastal_water",
    "water park": "coastal_water",
    "waterfall": "coastal_water",
    "watering hole": "coastal_water",
    "wave": "coastal_water",

    # ------------------------------------------------------------------
    # Public indoor / hospitality / institutional public scenes
    # ------------------------------------------------------------------
    "archive": "public_indoor",
    "atrium public": "public_indoor",
    "auditorium": "public_indoor",
    "bank vault": "public_indoor",
    "banquet hall": "public_indoor",
    "bar": "public_indoor",
    "beer garden": "public_indoor",
    "beer hall": "public_indoor",
    "berth": "public_indoor",
    "cafeteria": "public_indoor",
    "campus": "public_indoor",
    "clean room": "public_indoor",
    "conference center": "public_indoor",
    "conference room": "public_indoor",
    "corridor": "public_indoor",
    "courtyard": "public_indoor",
    "diner outdoor": "public_indoor",
    "dining hall": "public_indoor",
    "elevator door": "public_indoor",
    "elevator lobby": "public_indoor",
    "elevator shaft": "public_indoor",
    "entrance hall": "public_indoor",
    "escalator indoor": "public_indoor",
    "hotel outdoor": "public_indoor",
    "jail cell": "public_indoor",
    "library indoor": "public_indoor",
    "library outdoor": "public_indoor",
    "lobby": "public_indoor",
    "mezzanine": "public_indoor",
    "museum indoor": "public_indoor",
    "museum outdoor": "public_indoor",
    "nursing home": "public_indoor",
    "pavilion": "public_indoor",
    "pub indoor": "public_indoor",
    "reception": "public_indoor",
    "waiting room": "public_indoor",

    # ------------------------------------------------------------------
    # Education / health / office / laboratory scenes
    # ------------------------------------------------------------------
    "art school": "education_health_office",
    "biology laboratory": "education_health_office",
    "chemistry lab": "education_health_office",
    "classroom": "education_health_office",
    "computer room": "education_health_office",
    "hospital": "education_health_office",
    "hospital room": "education_health_office",
    "kindergarden classroom": "education_health_office",
    "lecture room": "education_health_office",
    "legislative chamber": "education_health_office",
    "office": "education_health_office",
    "office cubicles": "education_health_office",
    "operating room": "education_health_office",
    "physics laboratory": "education_health_office",
    "science museum": "education_health_office",
    "server room": "education_health_office",
    "veterinarians office": "education_health_office",

    # ------------------------------------------------------------------
    # Sports / recreation scenes
    # ------------------------------------------------------------------
    "arena hockey": "sports_recreation",
    "arena rodeo": "sports_recreation",
    "athletic field outdoor": "sports_recreation",
    "ball pit": "sports_recreation",
    "baseball field": "sports_recreation",
    "basketball court indoor": "sports_recreation",
    "bowling alley": "sports_recreation",
    "boxing ring": "sports_recreation",
    "bullring": "sports_recreation",
    "carrousel": "sports_recreation",
    "football field": "sports_recreation",
    "golf course": "sports_recreation",
    "gymnasium indoor": "sports_recreation",
    "ice skating rink indoor": "sports_recreation",
    "ice skating rink outdoor": "sports_recreation",
    "locker room": "sports_recreation",
    "martial arts gym": "sports_recreation",
    "picnic area": "sports_recreation",
    "playground": "sports_recreation",
    "racecourse": "sports_recreation",
    "sandbox": "sports_recreation",
    "ski resort": "sports_recreation",
    "ski slope": "sports_recreation",
    "soccer field": "sports_recreation",
    "stadium baseball": "sports_recreation",
    "stadium football": "sports_recreation",
    "stadium soccer": "sports_recreation",
    "swimming pool indoor": "sports_recreation",
    "swimming pool outdoor": "sports_recreation",
    "volleyball court outdoor": "sports_recreation",

    # ------------------------------------------------------------------
    # Industrial / workshop / infrastructure scenes
    # ------------------------------------------------------------------
    "army base": "industrial_workshop",
    "assembly line": "industrial_workshop",
    "auto factory": "industrial_workshop",
    "construction site": "industrial_workshop",
    "engine room": "industrial_workshop",
    "industrial area": "industrial_workshop",
    "junkyard": "industrial_workshop",
    "landfill": "industrial_workshop",
    "loading dock": "industrial_workshop",
    "oilrig": "industrial_workshop",
    "repair shop": "industrial_workshop",
    "wind farm": "industrial_workshop",

    # ------------------------------------------------------------------
    # Garden / park / designed green spaces
    # ------------------------------------------------------------------
    "botanical garden": "garden_park",
    "formal garden": "garden_park",
    "fountain": "garden_park",
    "gazebo exterior": "garden_park",
    "greenhouse indoor": "garden_park",
    "greenhouse outdoor": "garden_park",
    "japanese garden": "garden_park",
    "roof garden": "garden_park",
    "topiary garden": "garden_park",
    "zen garden": "garden_park",

    # ------------------------------------------------------------------
    # Entertainment / culture / performance scenes
    # ------------------------------------------------------------------
    "amphitheater": "entertainment_culture",
    "amusement arcade": "entertainment_culture",
    "amusement park": "entertainment_culture",
    "arcade": "entertainment_culture",
    "arena performance": "entertainment_culture",
    "art gallery": "entertainment_culture",
    "art studio": "entertainment_culture",
    "artists loft": "entertainment_culture",
    "ballroom": "entertainment_culture",
    "discotheque": "entertainment_culture",
    "movie theater indoor": "entertainment_culture",
    "music studio": "entertainment_culture",
    "natural history museum": "entertainment_culture",
    "orchestra pit": "entertainment_culture",
    "stage indoor": "entertainment_culture",
    "stage outdoor": "entertainment_culture",
    "television studio": "entertainment_culture",
}


def validate_places365_mapping() -> None:
    missing_values = [label for label, group in PLACES365_TO_SCENE_GROUP.items() if not group]
    if missing_values:
        raise RuntimeError(f"Places365 mapping has empty groups: {missing_values[:10]}")


validate_places365_mapping()


def allowed_places365_labels() -> tuple[str, ...]:
    """Return the Places365 scene labels Workflow A's VLM may choose from.

    Using this table (rather than the external ``categories_places365.txt``) as the
    allow-list guarantees every label the VLM can pick already resolves via
    ``scene_groups_for_label``.
    """
    return tuple(sorted(PLACES365_TO_SCENE_GROUP.keys()))
